// This file was generated by Prisma, and assumes you have installed:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    url: `sqlserver://${process.env.DATABASE_SERVER}:${process.env.DATABASE_PORT};database=${process.env.DATABASE_NAME};user=${process.env.DATABASE_USER};password=${process.env.DATABASE_PASSWORD};trustServerCertificate=true`,
  },
});